#!/bin/bash

#######################################################################
# Author: GwenDragon, <https://labs.gwendragon.de/blog/>
# License: GPL
#######################################################################

# 2021-06-25 removed custom.css support
#            commented custom.css shell commands
#            users can now use vivaldi://experiments to change CSS in UI

mod_dir=$(realpath "$(dirname $0)")
js_filename="char2workspace.js"
css_filename="css/nerd-font-on-workspace-icons.css"

vivaldi_installs=$(dirname $(find /opt -name "vivaldi-bin"))
vivaldi_install_dirs=($vivaldi_installs)

echo "---------------------"
count=1
selected=0
echo "Installations found:"
for dir in $vivaldi_installs; do
    echo $dir": "$count
    ((count++))
done
read -p "
Select installation to patch.
Input number and press [Enter] or [X] to cancel.
Input selection: " selected
if [ "$selected" = "X" ]; then
    exit
fi
((selected--))
if [ $selected -ge ${#vivaldi_install_dirs[@]} ]; then
    echo "Selection too large!"
fi
dir=${vivaldi_install_dirs[$selected]}
echo "---------------------
"
echo "Patch originating from "${mod_dir}" targeting "${vivaldi_install_dirs[$selected]}

sudo cp "$dir/resources/vivaldi/window.html" "$dir/resources/vivaldi/window.html-$(date +%Y-%m-%dT%H-%M-%S)"

alreadypatched=$(grep '<script src="custom.js"></script>' $dir/resources/vivaldi/window.html)
#alreadypatched=$(grep '<link rel="stylesheet" href="style/custom.css" />' $dir/resources/vivaldi/window.html);
if [ "$alreadypatched" = "" ]; then
    echo patching window.html
    #sudo sed -i -e 's/<\/head>/<link rel="stylesheet" href="style\/custom.css" \/> <\/head>/' "$dir/resources/vivaldi/window.html"
    sudo sed -i -e 's/<\/body>/<script src="custom.js"><\/script> <\/body>/' "$dir/resources/vivaldi/window.html"
else
    echo "window.html has already been patched!"
fi

if [ -f "$mod_dir/$css_filename" ] ; then
    echo "copying $css_filename"
    sudo cp -f "$mod_dir/$css_filename" "$dir/resources/vivaldi/style/custom.css"
else
    echo "$css_filename missing in $mod_dir"
fi

if [ -f "$mod_dir/$js_filename" ]; then
    echo "copying $js_filename"
    sudo cp -f "$mod_dir/$js_filename" "$dir/resources/vivaldi/custom.js"
else
    echo "$js_filename missing in $mod_dir"
fi
